version: '3.6'
services:
  dev:
    user: "${UID}:${GID}"
    build:
      context: ./docker
      args:
        - UID=${UID}
        - GID=${GID}
    volumes:
      - .:/app
    environment:
      LANG: ja_JP.UTF-8
      TZ: Asia/Tokyo
      RUST_BACKTRACE: 1
      RUST_LOG: vrc=debug
    dns:
      - 8.8.8.8
